### ISSUE TITLE
supression categorie - questionnaire / Back Office

### ISSUE THREAD

**Issue by Arnaudlaurent** [ExtiaPHP/techiteasy#4]
lorsque l'on veut supprimer une catégorie la suppression renvoi une erreur
![image](https://cloud.githubusercontent.com/assets/18571648/15030695/2fcdad52-1254-11e6-9d43-223c0d8673c6.png)

![image](https://cloud.githubusercontent.com/assets/18571648/15030704/4105c0a0-1254-11e6-9c43-3db0e545f25f.png)

lorsque l'on veut supprimer un questionnaire la suppression renvoi une erreur

![image](https://cloud.githubusercontent.com/assets/18571648/15030740/6510a528-1254-11e6-80d3-d1cf18f2950e.png)

**Comment by bricebauer** [comment]
résolue automatiquement avec la correction sur le delete on cascade du migrate
