### ISSUE TITLE
création de questionnaire / Back Office

### ISSUE THREAD

**Issue by Arnaudlaurent** [ExtiaPHP/techiteasy#8]
lorsque l'on crée un questionnaire
1.  faire un premier filtre en sélectionnant les catégorie de questions.
2. afficher toutes les questions de la catégorie filtrée
3. sélectionner celle que l'on veut intégrer dans son questionnaire (max 30 questions sélectionnables)

il faut dans le filtre afficher : 
                                                    N°| la question |  la description  | la difficultée
                                 exemple :   1  | connais tu le QHSSE ? | sécurité | intermediaire

**Comment by bricebauer** [comment]
corrigé et mis en place
